// Random initial board state
export const initialBoard = [
  [
    { color: "light", piece: null },
    { color: "dark", piece: null },
    { color: "light", piece: null },
    { color: "dark", piece: null },
    { color: "light", piece: null },
    { color: "dark", piece: null },
    { color: "light", piece: null },
    { color: "dark", piece: null },
  ],
  [
    { color: "dark", piece: { type: "knight", color: "black" } },
    { color: "light", piece: null },
    { color: "dark", piece: null },
    { color: "light", piece: null },
    { color: "dark", piece: null },
    { color: "light", piece: { type: "queen", color: "black" } },
    { color: "dark", piece: null },
    { color: "light", piece: { type: "knight", color: "black" } },
  ],
  [
    { color: "light", piece: null },
    { color: "dark", piece: null },
    { color: "light", piece: null },
    { color: "dark", piece: null },
    { color: "light", piece: null },
    { color: "dark", piece: null },
    { color: "light", piece: null },
    { color: "dark", piece: null },
  ],
  [
    { color: "dark", piece: null },
    { color: "light", piece: null },
    { color: "dark", piece: null },
    { color: "light", piece: null },
    { color: "dark", piece: null },
    { color: "light", piece: null },
    { color: "dark", piece: null },
    { color: "light", piece: null },
  ],
  [
    { color: "light", piece: null },
    { color: "dark", piece: null },
    { color: "light", piece: null },
    { color: "dark", piece: null },
    { color: "light", piece: null },
    { color: "dark", piece: null },
    { color: "light", piece: null },
    { color: "dark", piece: null },
  ],
  [
    { color: "dark", piece: null },
    { color: "light", piece: null },
    { color: "dark", piece: null },
    { color: "light", piece: null },
    { color: "dark", piece: null },
    { color: "light", piece: null },
    { color: "dark", piece: null },
    { color: "light", piece: null },
  ],
  [
    { color: "light", piece: { type: "knight", color: "white" } },
    { color: "dark", piece: null },
    { color: "light", piece: null },
    { color: "dark", piece: { type: "queen", color: "white" } },
    { color: "light", piece: null },
    { color: "dark", piece: null },
    { color: "light", piece: null },
    { color: "dark", piece: { type: "knight", color: "white" } },
  ],
  [
    { color: "dark", piece: null },
    { color: "light", piece: null },
    { color: "dark", piece: null },
    { color: "light", piece: null },
    { color: "dark", piece: null },
    { color: "light", piece: null },
    { color: "dark", piece: null },
    { color: "light", piece: null },
  ],
];
