version: "3.8"
services:
    api:
        build:
            dockerfile: Dockerfile
            context: .
        depends_on: 
            - postgres
        environment: 
            DATABASE_URL: postgres://root:root@postgres:5432/db
            NODE_ENV: development
            PORT: 3000
        ports:
            - "8080:3000"

    postgres:
        image: postgres:15
        ports:
            - "5432:5432"
        environment: 
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: db