version: "3.8"
services:
    api:
        build:
            dockerfile: Dockerfile
            context: .
        
        depends_on: 
            - postgres
        environment: 
            DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}
            NODE_ENV: ${NODE_ENV}
            PORT: ${PORT}
        ports:
            - "${PORT}:${PORT}"
    postgres:
        image: postgres:15
        ports:
            - "${POSTGRES_PORT}:${POSTGRES_PORT}"
        environment: 
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}